// Sears Modern Homes (1908-1940) Architectural Data & Historical Catalog Catalog.
//
// Ground truth historical provenance for parametric 3D reconstruction of
// Craftsman Bungalow homes (The Ashmore, The Osborn, The Rodessa, The Valmont).
// All dimensions are referenced to authentic Sears catalog floor plans with
// real metric conversions.

export interface CraftsmanPieceInfo {
  id: string;
  name: string;
  room: "porch" | "living" | "dining" | "kitchen" | "hallway" | "bedroom" | "bathroom";
  catalogModel: string;
  catalogYear: number;
  woodSpecies: string;
  joinery: string;
  finish: string;
  description: string;
  dimensionsMeters: [number, number, number]; // [width, depth, height]
  historicalPrice: string;
}

export const SEARS_CRAFTSMAN_CATALOG: Record<string, CraftsmanPieceInfo> = {
  "fireplace-inglenook": {
    id: "fireplace-inglenook",
    name: "Clinker Brick & Riverstone Inglenook Fireplace",
    room: "living",
    catalogModel: "Sears Honor Bilt No. 1324",
    catalogYear: 1928,
    woodSpecies: "Quartersawn White Oak (Fumed)",
    joinery: "Corbeled solid beam with mortise & tenon",
    finish: "Hand-rubbed fumed oil & dark wax",
    description: "Massive clinker brick fireplace with recessed firebox, corbeled solid oak mantel shelf, and flanked by built-in inglenook fireside settle benches.",
    dimensionsMeters: [2.36, 0.65, 2.6],
    historicalPrice: "$48.50 (in 1928 kit)",
  },
  "stickley-morris-chair": {
    id: "stickley-morris-chair",
    name: "Gustav Stickley No. 369 Reclining Morris Chair",
    room: "living",
    catalogModel: "Craftsman Furniture Series No. 369",
    catalogYear: 1926,
    woodSpecies: "Quartersawn White Oak",
    joinery: "Through-tenon pinned joinery with keyed slats",
    finish: "Fumed dark ammonia fumed oak with shellac",
    description: "Iconic Arts & Crafts armchair with 4-position reclining back, heavy 4-inch wide armrests, side slats, and brown saddle leather cushion.",
    dimensionsMeters: [0.92, 0.96, 0.98],
    historicalPrice: "$24.75",
  },
  "mission-settle-sofa": {
    id: "mission-settle-sofa",
    name: "Craftsman Mission 3-Seat Settle Sofa",
    room: "living",
    catalogModel: "Sears Mission Line No. 814",
    catalogYear: 1928,
    woodSpecies: "Quartersawn White Oak",
    joinery: "Blind mortise-and-tenon with edge chamfers",
    finish: "Dark Mission brown stain",
    description: "Sturdy three-seat settle featuring vertical back and side slats, broad arm rails, and deep cushions upholstered in olive wool rep fabric.",
    dimensionsMeters: [1.82, 0.88, 0.86],
    historicalPrice: "$38.00",
  },
  "library-table": {
    id: "library-table",
    name: "Craftsman Library & Book Table",
    room: "living",
    catalogModel: "Honor Bilt Table No. 402",
    catalogYear: 1928,
    woodSpecies: "Solid White Oak",
    joinery: "Through-tenons with walnut locking keys",
    finish: "Golden oak satin varnish",
    description: "Solid 2-inch top library table with lower stretcher magazine shelf, square legs, and prominent through-tenons showing authentic craft construction.",
    dimensionsMeters: [1.32, 0.72, 0.76],
    historicalPrice: "$16.25",
  },
  "amber-mica-lamp": {
    id: "amber-mica-lamp",
    name: "Dirk van Erp Hammered Copper & Amber Mica Lamp",
    room: "living",
    catalogModel: "San Francisco Arts & Crafts Workshop Style",
    catalogYear: 1925,
    woodSpecies: "Hand-hammered copper / Mineral Mica",
    joinery: "Riveted copper strapping over sheet mica",
    finish: "Fire-patinated dark chocolate bronze",
    description: "Hand-hammered conical four-panel amber mineral mica shade that emits a warm, soothing golden incandescent glow when lit.",
    dimensionsMeters: [0.46, 0.46, 0.58],
    historicalPrice: "$18.50",
  },
  "dining-trestle-table": {
    id: "dining-trestle-table",
    name: "Craftsman Extension Dining Table",
    room: "dining",
    catalogModel: "Sears Dining Suite No. 620",
    catalogYear: 1928,
    woodSpecies: "Quartersawn White Oak",
    joinery: "Trestle base with pinned through-tenon stretcher",
    finish: "Nut brown satin lacquer",
    description: "Heavy oak dining table with substantial end trestles, keyed center stretcher, and matching slatted high-back dining chairs.",
    dimensionsMeters: [1.68, 0.94, 0.76],
    historicalPrice: "$32.50",
  },
  "china-buffet-sideboard": {
    id: "china-buffet-sideboard",
    name: "Built-In Craftsman China Buffet & Sideboard",
    room: "dining",
    catalogModel: "Sears Ashmore Built-in Buffet",
    catalogYear: 1928,
    woodSpecies: "Quartersawn White Oak",
    joinery: "Dovetail drawer boxes with leaded glass doors",
    finish: "Dark fumed oak with antique brass bail pulls",
    description: "Full architectural built-in sideboard with leaded art glass display cabinets, beveled mirror splashback, five linen drawers, and lower double cupboards.",
    dimensionsMeters: [2.1, 0.52, 1.85],
    historicalPrice: "$65.00 (built-in kit)",
  },
  "hoosier-cabinet": {
    id: "hoosier-cabinet",
    name: "Hoosier 'Special' Kitchen Cabinet Workstation",
    room: "kitchen",
    catalogModel: "Hoosier Mfg. Co. / Sears Catalog No. 901",
    catalogYear: 1927,
    woodSpecies: "Northern Hard Maple & White Enamel",
    joinery: "Tambour roll-front with tongue-and-groove casing",
    finish: "Pure white porcelain enamel & gloss enamel",
    description: "The ultimate 1920s kitchen command center: porcelain enamel slide-out worktable, roll-curtain flour sifter bin, spice carousel, and glassware cupboards.",
    dimensionsMeters: [1.22, 0.72, 1.78],
    historicalPrice: "$42.50",
  },
  "glenwood-stove": {
    id: "glenwood-stove",
    name: "Glenwood 4-Burner Cast Iron & Enamel Gas Range",
    room: "kitchen",
    catalogModel: "Glenwood Modern Kitchen Range No. 4",
    catalogYear: 1928,
    woodSpecies: "Cast Iron & Vitreous Porcelain Enamel",
    joinery: "Interlocking cast panels with nickel-plated legs",
    finish: "White porcelain and black iron with temperature gauge",
    description: "Period gas range with four cooktop burners, high warming closet, elevated baking oven, and thermometer gauge on cabriole cast iron legs.",
    dimensionsMeters: [0.95, 0.72, 1.35],
    historicalPrice: "$56.00",
  },
  "farmhouse-sink": {
    id: "farmhouse-sink",
    name: "Standard Sanitary Apron-Front Porcelain Sink",
    room: "kitchen",
    catalogModel: "Standard Sanitary Mfg. No. 102",
    catalogYear: 1928,
    woodSpecies: "Heavy Enameled Cast Iron",
    joinery: "Integrated fluted drainboard with wall hanger",
    finish: "Vitreous china white with brass fixtures",
    description: "Deep single-basin apron-front kitchen sink with integral left-hand fluted ribbed drainboard and dual compression porcelain hot/cold bibb faucets.",
    dimensionsMeters: [1.35, 0.58, 0.88],
    historicalPrice: "$29.50",
  },
  "porch-swing": {
    id: "porch-swing",
    name: "Mission Slatted Front Porch Swing",
    room: "porch",
    catalogModel: "Honor Bilt Veranda Series No. 71",
    catalogYear: 1928,
    woodSpecies: "Cypress & White Oak",
    joinery: "Reinforced mortise & tenon with heavy eye bolts",
    finish: "Spar varnish weather-resistant dark oak",
    description: "Generous 5-foot slatted porch swing suspended from the beadboard porch ceiling by solid brass chains, featuring rolled armrests and canvas cushions.",
    dimensionsMeters: [1.55, 0.65, 0.58],
    historicalPrice: "$11.75",
  },
  "craftsman-bedstead": {
    id: "craftsman-bedstead",
    name: "Roycroft Style Slatted Queen Bedstead",
    room: "bedroom",
    catalogModel: "Sears Chamber Suite No. 312",
    catalogYear: 1928,
    woodSpecies: "Quartersawn White Oak",
    joinery: "Bed-bolt fastened corner posts with vertical slats",
    finish: "Hand-rubbed wax on fumed oak",
    description: "Substantial Craftsman queen bedstead with high slatted headboard, matching footboard, stout square posts, and period patchwork quilt.",
    dimensionsMeters: [1.62, 2.12, 1.25],
    historicalPrice: "$28.50",
  },
  "clawfoot-bathtub": {
    id: "clawfoot-bathtub",
    name: "Cast Iron Porcelain Enamel Clawfoot Soaking Tub",
    room: "bathroom",
    catalogModel: "Standard Sanitary 'Empire' Roll-Rim Tub",
    catalogYear: 1928,
    woodSpecies: "Enameled Cast Iron / Polished Nickel",
    joinery: "Ball-and-claw cast iron feet with lock bolts",
    finish: "High-gloss vitreous enamel and polished nickel",
    description: "5.5-foot roll-rim soaking bathtub with ornate eagle-claw-on-ball feet, exterior white enamel, and telephone-cradle hand shower fixtures.",
    dimensionsMeters: [1.68, 0.76, 0.62],
    historicalPrice: "$36.00",
  },
};

export const ROOM_ARCHITECTURAL_DETAILS = [
  {
    id: "living",
    name: "Living Room (Parlor)",
    icon: "couch",
    description: "Central gathering room with quartersawn white oak flooring, 1.35m board-and-batten wainscoting, inglenook brick fireplace, and exposed coffered ceiling box beams.",
    areaSqM: 23.5,
    ceilingHeightM: 2.85,
    focalFeatures: ["Clinker brick fireplace", "Coffered ceiling box beams", "Stickley Morris armchair", "Dirk van Erp mica lamp"],
  },
  {
    id: "dining",
    name: "Formal Dining Room",
    icon: "utensils",
    description: "Connected to living room via cased colonnade bookcases. Features built-in leaded glass china buffet, heavy trestle dining table, and amber glass pendant chandelier.",
    areaSqM: 16.2,
    ceilingHeightM: 2.85,
    focalFeatures: ["Built-in china buffet", "Trestle table & 6 chairs", "Colonnade room divider", "Leaded casement windows"],
  },
  {
    id: "kitchen",
    name: "Craftsman Kitchen & Pantry",
    icon: "chef-hat",
    description: "Period culinary workstation equipped with a Hoosier cabinet, Glenwood 4-burner cast iron gas range, apron-front farmhouse porcelain sink, and butcher block island.",
    areaSqM: 14.8,
    ceilingHeightM: 2.85,
    focalFeatures: ["Hoosier baking cabinet", "Cast iron cooking stove", "Apron-front sink", "Butcher block island"],
  },
  {
    id: "porch",
    name: "Front Veranda / Porch",
    icon: "sun",
    description: "Deep covered front porch with riverstone foundation piers, double square wood columns, slatted cypress porch swing, and fir tongue-and-groove decking.",
    areaSqM: 12.4,
    ceilingHeightM: 2.65,
    focalFeatures: ["Riverstone piers & columns", "Slatted porch swing", "Beaded ceiling & lantern", "Craftsman entry door"],
  },
  {
    id: "bedroom",
    name: "Master Bedroom",
    icon: "bed",
    description: "Restful retreat with quartersawn oak slatted queen bedstead, nightstands with brass/mica lamps, 5-drawer bureau with swivel mirror, and double wardrobe.",
    areaSqM: 15.6,
    ceilingHeightM: 2.85,
    focalFeatures: ["Oak slatted bedstead", "5-drawer bureau & mirror", "Double wardrobe", "Bedside mica lamps"],
  },
  {
    id: "bathroom",
    name: "Craftsman Bathroom",
    icon: "bath",
    description: "Period bathroom featuring white subway tile wainscoting with black trim, hexagonal porcelain mosaic floor, clawfoot cast-iron tub, and pedestal sink.",
    areaSqM: 6.8,
    ceilingHeightM: 2.85,
    focalFeatures: ["Clawfoot cast-iron tub", "Hex mosaic tile floor", "Subway tile wainscoting", "Pedestal washbasin"],
  },
  {
    id: "cutaway",
    name: "Full Dollhouse Cutaway",
    icon: "home",
    description: "Complete isometric architectural cutaway of the entire 1928 Sears Craftsman Bungalow, showing all 7 furnished rooms, floorplan circulation, and walking pathways.",
    areaSqM: 95.0,
    ceilingHeightM: 3.2,
    focalFeatures: ["All 7 rooms simultaneously", "Continuous circulation paths", "Wall cross-sections", "Exterior roof eaves & foundation"],
  },
] as const;
