// GaitTransformer browser-side forward inference (cmaes-ablation-real).
//
// EXACT mirror of the training-side forward pass in sibling crate
// fs-g1-train/src/transformer.rs (RMSNorm eps 1e-6, rotate-half RoPE base
// 10000, GQA 8 query / 4 KV heads, causal windowed attention with context
// 64, SwiGLU MLP, tanh policy head, linear value head). Weights come from
// `public/robots/g1/transformer/g1-ablation-weights-v1.bin`, exported by
// `fs-g1-train/examples/train_ablation.rs` — the layout contract is the
// length-prefixed f32 dump documented in `dump_weights` there.
//
// Parity: tests/gaitTransformer.test.ts checks this forward pass against
// golden vectors generated by the Rust binary from the SAME weight file
// (tolerance 1e-3 abs; JS accumulates in f64, Rust in f32).
//
// Numeric note: JS numbers are f64, so accumulation order semantics differ
// slightly from the f32 training path. That drift is bounded (~1e-6 after
// tanh) and disclosed; the training receipt ships both sides' greedy metrics
// so behavior-level drift is checkable, not assumed away.

export interface GaitTransformerConfig {
  dModel: number;
  nHeads: number;
  headDim: number;
  nKvHeads: number;
  kvDim: number;
  nLayers: number;
  mlpHidden: number;
  context: number;
  nInputs: number;
  nOutputs: number;
}

export interface TransformerObsNorm {
  mean: Float32Array;
  variance: Float32Array;
}

export interface LoadedTransformerWeights {
  config: GaitTransformerConfig;
  embed: Float32Array; // dModel × nInputs
  layers: Array<{
    wq: Float32Array; // dModel × dModel
    wk: Float32Array; // kvDim × dModel
    wv: Float32Array; // kvDim × dModel
    wo: Float32Array; // dModel × dModel
    wGate: Float32Array; // mlpHidden × dModel
    wUp: Float32Array; // mlpHidden × dModel
    wDown: Float32Array; // dModel × mlpHidden
    norm1: Float32Array; // dModel
    norm2: Float32Array; // dModel
  }>;
  finalNorm: Float32Array; // dModel
  policyHead: Float32Array; // nOutputs × dModel
  valueW: Float32Array; // dModel
  valueB: number;
  obsNorm: TransformerObsNorm;
}

const MAGIC = 0x54475346; // "FSGT" bytes read as a little-endian u32

/**
 * Audited architecture pin — the ONLY weights this loader accepts, exactly
 * like the kernel-version pins in frankensimCmaes.ts. Anything else fails
 * closed: the shipped artifact must be the fs-g1-train-trained,
 * golden-parity-gated model, not whatever bin happens to sit at the path.
 * Regenerate via fs-g1-train/examples/{train_ablation,finalize_ablation}.
 */
const AUDITED_CONFIG: GaitTransformerConfig = {
  dModel: 256,
  nHeads: 8,
  headDim: 32,
  nKvHeads: 4,
  kvDim: 128,
  nLayers: 4,
  mlpHidden: 682,
  context: 64,
  nInputs: 42,
  nOutputs: 29,
};

class WeightsReader {
  private view: DataView;
  private pos = 0;

  constructor(private bytes: Uint8Array) {
    this.view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  }

  u32(): number {
    const v = this.view.getUint32(this.pos, true);
    this.pos += 4;
    return v;
  }

  f32Array(): Float32Array {
    const len = this.u32();
    const expectedBytes = len * 4;
    if (this.pos + expectedBytes > this.bytes.byteLength) {
      throw new Error(`weights file truncated: need ${expectedBytes} bytes at ${this.pos}`);
    }
    const out = new Float32Array(len);
    for (let i = 0; i < len; i++) {
      out[i] = this.view.getFloat32(this.pos + i * 4, true);
    }
    this.pos += expectedBytes;
    return out;
  }

  expectU32(value: number, label: string): void {
    const got = this.u32();
    if (got !== value) {
      throw new Error(`weights file mismatch at ${label}: expected ${value}, got ${got}`);
    }
  }

  atEnd(): boolean {
    return this.pos === this.bytes.byteLength;
  }
}

/**
 * Fail-closed weights loader: any magic/version/dimension/array-length
 * mismatch throws. Never returns a partially-populated structure.
 */
export function loadGaitTransformerWeights(buffer: ArrayBuffer): LoadedTransformerWeights {
  const bytes = new Uint8Array(buffer);
  if (bytes.byteLength < 4 + 4 + 40 + 4) {
    throw new Error("weights file too small");
  }
  const reader = new WeightsReader(bytes);
  reader.expectU32(MAGIC, "magic");
  reader.expectU32(1, "layoutVersion");
  const dims: number[] = [];
  for (let i = 0; i < 10; i++) dims.push(reader.u32());
  const dimNames = [
    "dModel",
    "nHeads",
    "headDim",
    "nKvHeads",
    "kvDim",
    "nLayers",
    "mlpHidden",
    "context",
    "nInputs",
    "nOutputs",
  ] as const;
  for (let i = 0; i < dimNames.length; i++) {
    if (dims[i] !== AUDITED_CONFIG[dimNames[i]]) {
      throw new Error(
        `weights file ${dimNames[i]}=${dims[i]} != audited ${AUDITED_CONFIG[dimNames[i]]} — foreign or stale artifact; regenerate via fs-g1-train/examples/{train_ablation,finalize_ablation}`,
      );
    }
  }
  const [dModel, nHeads, headDim, nKvHeads, kvDim, nLayers, mlpHidden, context, nInputs, nOutputs] = dims;
  const layerArrays: LoadedTransformerWeights["layers"] = [];
  const expectedShape = (rows: number, cols: number) => rows * cols;
  const arrayCount = reader.u32();
  const expectedArrays = 2 + nLayers * 9 + 5;
  if (arrayCount !== expectedArrays) {
    throw new Error(`array count ${arrayCount} != expected ${expectedArrays}`);
  }

  const embed = reader.f32Array();
  if (embed.length !== expectedShape(dModel, nInputs)) throw new Error("embed shape");
  for (let l = 0; l < nLayers; l++) {
    const layer = {
      wq: reader.f32Array(),
      wk: reader.f32Array(),
      wv: reader.f32Array(),
      wo: reader.f32Array(),
      wGate: reader.f32Array(),
      wUp: reader.f32Array(),
      wDown: reader.f32Array(),
      norm1: reader.f32Array(),
      norm2: reader.f32Array(),
    };
    if (layer.wq.length !== expectedShape(dModel, dModel)) throw new Error(`layer ${l} wq`);
    if (layer.wk.length !== expectedShape(kvDim, dModel)) throw new Error(`layer ${l} wk`);
    if (layer.wv.length !== expectedShape(kvDim, dModel)) throw new Error(`layer ${l} wv`);
    if (layer.wo.length !== expectedShape(dModel, dModel)) throw new Error(`layer ${l} wo`);
    if (layer.wGate.length !== expectedShape(mlpHidden, dModel)) throw new Error(`layer ${l} wGate`);
    if (layer.wUp.length !== expectedShape(mlpHidden, dModel)) throw new Error(`layer ${l} wUp`);
    if (layer.wDown.length !== expectedShape(dModel, mlpHidden)) throw new Error(`layer ${l} wDown`);
    if (layer.norm1.length !== dModel || layer.norm2.length !== dModel) throw new Error(`layer ${l} norms`);
    layerArrays.push(layer);
  }
  const finalNorm = reader.f32Array();
  if (finalNorm.length !== dModel) throw new Error("finalNorm");
  const policyHead = reader.f32Array();
  if (policyHead.length !== expectedShape(nOutputs, dModel)) throw new Error("policyHead");
  const valueW = reader.f32Array();
  if (valueW.length !== dModel) throw new Error("valueW");
  const valueBArr = reader.f32Array();
  if (valueBArr.length !== 1) throw new Error("valueB");
  const obsMean = reader.f32Array();
  const obsVar = reader.f32Array();
  if (obsMean.length !== nInputs || obsVar.length !== nInputs) throw new Error("obsNorm");
  if (!reader.atEnd()) throw new Error("trailing bytes in weights file");

  return {
    config: { dModel, nHeads, headDim, nKvHeads, kvDim, nLayers, mlpHidden, context, nInputs, nOutputs },
    embed,
    layers: layerArrays,
    finalNorm,
    policyHead,
    valueW,
    valueB: valueBArr[0],
    obsNorm: { mean: obsMean, variance: obsVar },
  };
}

function matvec(out: Float64Array, w: Float32Array, rows: number, cols: number, x: Float64Array): void {
  for (let r = 0; r < rows; r++) {
    let sum = 0.0;
    const base = r * cols;
    for (let c = 0; c < cols; c++) sum += w[base + c] * x[c];
    out[r] = sum;
  }
}

function rmsNorm(h: Float64Array, weight: Float32Array): void {
  let meanSq = 0.0;
  const n = h.length;
  for (let i = 0; i < n; i++) meanSq += h[i] * h[i];
  meanSq /= n;
  const invRms = 1.0 / Math.sqrt(meanSq + 1e-6);
  for (let i = 0; i < n; i++) h[i] *= invRms * weight[i];
}

function ropeInPlace(x: Float64Array, headDim: number, position: number): void {
  const half = headDim / 2;
  for (let base = 0; base < x.length; base += headDim) {
    for (let i = 0; i < half; i++) {
      const freq = Math.pow(10000.0, (-2.0 * i) / half);
      const angle = position * freq;
      const c = Math.cos(angle);
      const s = Math.sin(angle);
      const x0 = x[base + i];
      const x1 = x[base + i + half];
      x[base + i] = x0 * c - x1 * s;
      x[base + i + half] = x0 * s + x1 * c;
    }
  }
}

interface KvWindow {
  k: Float32Array; // context × kvDim
  v: Float32Array;
  start: number; // absolute position of slot 0
  count: number;
}

/**
 * Sequential policy inference over the windowed KV cache — one action per
 * call, mirroring `GaitTransformer::forward_step`. `position` is the ABSOLUTE
 * step index (drives RoPE), matching the training-side convention.
 */
export class GaitTransformerPolicy {
  readonly config: GaitTransformerConfig;
  private w: LoadedTransformerWeights;
  private caches: KvWindow[];
  private h: Float64Array;
  private scratch: Float64Array;
  private q: Float64Array;
  private k: Float64Array;
  private v: Float64Array;
  private attn: Float64Array;
  private proj: Float64Array;
  private gate: Float64Array;
  private up: Float64Array;
  private mid: Float64Array;
  private normedObs: Float64Array;

  constructor(weights: LoadedTransformerWeights) {
    this.w = weights;
    this.config = weights.config;
    const d = this.config.dModel;
    const kv = this.config.kvDim;
    const mlp = this.config.mlpHidden;
    this.caches = this.config.nLayers > 0 ? this.makeCaches() : [];
    this.h = new Float64Array(d);
    this.scratch = new Float64Array(d);
    this.q = new Float64Array(d);
    this.k = new Float64Array(kv);
    this.v = new Float64Array(kv);
    this.attn = new Float64Array(d);
    this.proj = new Float64Array(d);
    this.gate = new Float64Array(mlp);
    this.up = new Float64Array(mlp);
    this.mid = new Float64Array(mlp);
    this.normedObs = new Float64Array(this.config.nInputs);
  }

  private makeCaches(): KvWindow[] {
    const kv = this.config.kvDim;
    const ctx = this.config.context;
    return Array.from({ length: this.config.nLayers }, () => ({
      k: new Float32Array(kv * ctx),
      v: new Float32Array(kv * ctx),
      start: 0,
      count: 0,
    }));
  }

  /**
   * The final hidden state from the most recent `step`, copied.
   *
   * The policy head is a linear map from exactly this vector, so fitting a head
   * offline needs these features. Read-only and unused by inference; see
   * scripts/fit-transformer-head.ts.
   */
  hiddenState(): Float64Array {
    return Float64Array.from(this.h);
  }

  reset(): void {
    for (const c of this.caches) {
      c.start = 0;
      c.count = 0;
    }
  }

  step(obs: ArrayLike<number>, position: number): { action: Float64Array; value: number } {
    const cfg = this.config;
    const d = cfg.dModel;
    if (obs.length !== cfg.nInputs) {
      throw new Error(`obs dim ${obs.length} != ${cfg.nInputs}`);
    }
    for (let i = 0; i < cfg.nInputs; i++) {
      this.normedObs[i] = (obs[i] - this.w.obsNorm.mean[i]) / (Math.sqrt(this.w.obsNorm.variance[i]) + 1e-8);
    }
    matvec(this.h, this.w.embed, d, cfg.nInputs, this.normedObs);

    for (let li = 0; li < cfg.nLayers; li++) {
      const layer = this.w.layers[li];
      this.scratch.set(this.h);
      rmsNorm(this.scratch, layer.norm1);
      matvec(this.q, layer.wq, d, d, this.scratch);
      matvec(this.k, layer.wk, cfg.kvDim, d, this.scratch);
      matvec(this.v, layer.wv, cfg.kvDim, d, this.scratch);
      ropeInPlace(this.q, cfg.headDim, position);
      ropeInPlace(this.k, cfg.headDim, position);
      this.cachePush(this.caches[li], this.k, this.v);
      this.attend(this.caches[li], layer);
      matvec(this.proj, layer.wo, d, d, this.attn);
      for (let i = 0; i < d; i++) this.h[i] += this.proj[i];

      this.scratch.set(this.h);
      rmsNorm(this.scratch, layer.norm2);
      matvec(this.gate, layer.wGate, cfg.mlpHidden, d, this.scratch);
      matvec(this.up, layer.wUp, cfg.mlpHidden, d, this.scratch);
      for (let i = 0; i < cfg.mlpHidden; i++) {
        const g = this.gate[i];
        this.mid[i] = (g / (1.0 + Math.exp(-g))) * this.up[i];
      }
      matvec(this.proj, layer.wDown, d, cfg.mlpHidden, this.mid);
      for (let i = 0; i < d; i++) this.h[i] += this.proj[i];
    }

    rmsNorm(this.h, this.w.finalNorm);
    const action = new Float64Array(cfg.nOutputs);
    for (let o = 0; o < cfg.nOutputs; o++) {
      let sum = 0.0;
      const base = o * d;
      for (let c = 0; c < d; c++) sum += this.w.policyHead[base + c] * this.h[c];
      action[o] = Math.tanh(sum);
    }
    let value = this.w.valueB;
    for (let c = 0; c < d; c++) value += this.w.valueW[c] * this.h[c];
    return { action, value };
  }

  private cachePush(cache: KvWindow, k: Float64Array, v: Float64Array): void {
    const kvDim = this.config.kvDim;
    if (cache.count === this.config.context) {
      cache.k.copyWithin(0, kvDim);
      cache.v.copyWithin(0, kvDim);
      cache.start += 1;
      cache.count -= 1;
    }
    const off = cache.count * kvDim;
    for (let i = 0; i < kvDim; i++) {
      cache.k[off + i] = k[i];
      cache.v[off + i] = v[i];
    }
    cache.count += 1;
  }

  /** Causal GQA attention over the window — mirror of `attention_causal`. */
  private attend(cache: KvWindow, layer: LoadedTransformerWeights["layers"][number]): void {
    const { nHeads, headDim, kvDim } = this.config;
    const count = cache.count;
    const nQGroups = nHeads / (kvDim / headDim);
    const scale = 1.0 / Math.sqrt(headDim);
    const scores = new Float64Array(count);
    for (let g = 0; g < nHeads; g++) {
      const kvHead = Math.floor(g / nQGroups);
      const qOff = g * headDim;
      let maxs = -Infinity;
      for (let j = 0; j < count; j++) {
        const ko = j * kvDim + kvHead * headDim;
        let s = 0.0;
        for (let i = 0; i < headDim; i++) s += this.q[qOff + i] * cache.k[ko + i];
        s *= scale;
        scores[j] = s;
        if (s > maxs) maxs = s;
      }
      let sum = 0.0;
      for (let j = 0; j < count; j++) {
        const e = Math.exp(scores[j] - maxs);
        scores[j] = e;
        sum += e;
      }
      const inv = 1.0 / sum;
      const vo = kvHead * headDim;
      for (let i = 0; i < headDim; i++) this.attn[qOff + i] = 0.0;
      for (let j = 0; j < count; j++) {
        const a = scores[j] * inv;
        const voJ = j * kvDim + vo;
        for (let i = 0; i < headDim; i++) this.attn[qOff + i] += a * cache.v[voJ + i];
      }
    }
  }
}

/** Default artifact path, relative to the site root. */
export const TRANSFORMER_WEIGHTS_URL = "/robots/g1/transformer/g1-ablation-weights-v2.bin";

export async function fetchDefaultTransformerWeights(): Promise<LoadedTransformerWeights> {
  const res = await fetch(TRANSFORMER_WEIGHTS_URL);
  if (!res.ok) {
    throw new Error(`transformer weights fetch failed: ${res.status} ${res.statusText}`);
  }
  return loadGaitTransformerWeights(await res.arrayBuffer());
}
