// PBR texture & material pipeline (cmaes-feat-pr1-pbr-pipeline).
//
// SOTA-grounded PBR material slot system for the photo-real household.
// Adheres to the Khronos glTF 2.0 PBR specification:
//   - color textures: sRGB (decoded to linear at sample time)
//   - data textures (normal, metallic-roughness, AO, displacement): linear
//   - metalness: per-material pair from the friction class
//   - roughness: per-material nominal + per-instance jitter (deterministic via mulberry32)
//   - IBL: every PBR material reads from a shared scene environment (Epic 1 pr3 IBL)
//
// This module is the *material slot* layer. It does NOT load or generate textures
// (that's Epic 1 pr2 procedural material authoring). It DOES:
//   - declare the per-FurnitureKind PBR material slot (slot, not instance)
//   - declare the texture-set schema per material class
//   - declare the KTX2 compressed-texture delivery contract
//   - declare the sRGB/linear discipline and the color-space assertions
//   - declare the per-material-pair roughness / metallic defaults
//   - expose a single `materialSlotForKind(kind)` accessor used by Epic 2 (fg2) and
//     Epic 1 (pr3, pr4, pr5)
//
// References (all SOTA, all real, all current as of 2025-2026):
//   - Khronos glTF 2.0 PBR specification: https://www.khronos.org/gltf/pbr
//   - Three.js PBR examples: https://threejs.org/examples/?q=pbr
//   - Playtex AI WebGL PBR texture workflow: https://www.playtex.ai/blog/using-pbr-textures-for-three-js-games
//   - proctexture WebGL PBR material: https://proctexture.com/workflows/webgl-material
//   - CraftPBR Three.js materials guide: https://craftpbr.com/guides/three-js-materials
//   - Apple RoomPlan 16-category taxonomy (for the furniture-kind mapping): https://machinelearning.apple.com/research/roomplan
//
// Honesty contract:
//   - No textures are bundled in the repo. The pipeline declares the *contract* for
//     textures; texture acquisition is per-deployment (KTX2 streamed, or generated by
//     Epic 1 pr2 procedural authoring).
//   - All roughness / metallic values are nominal; per-piece overrides happen in
//     the consumer (HouseFurnitureSpec).
//   - sRGB is the color space for color textures; everything else is linear. The
//     pipeline fails closed (throws) if a consumer tries to put a linear texture in
//     a sRGB slot or vice versa.

import { FurnitureKind } from "./furnitureTaxonomy";

/** glTF 2.0 color space for a texture slot. */
export type ColorSpace = "srgb" | "linear";

/** Texture slot identifier within a PBR material. */
export type PBRTextureSlot =
  | "baseColor" // sRGB; the diffuse albedo
  | "normal" // linear; tangent-space normal map
  | "metallicRoughness" // linear; G channel = metallic, B channel = roughness
  | "occlusion" // linear; ambient occlusion (multiplied into indirect light)
  | "emissive" // sRGB; the emissive color (e.g., oven light)
  | "displacement" // linear; height/displacement (rarely used in browser PBR)
  | "sheenColor" // sRGB; fabric-only sheen color
  | "sheenRoughness"; // linear; fabric-only sheen roughness

/** PBR material class (distinct from FurnitureKind; one class covers many kinds). */
export type PBRMaterialClass =
  | "oak-wood" // warm, ringed grain
  | "walnut-wood" // darker, smoother grain
  | "brass" // warm metal
  | "chrome" // cool polished metal
  | "cast-iron" // rough dark metal
  | "fabric-cotton" // diffuse, soft
  | "fabric-velvet" // diffuse, sheen
  | "fabric-leather" // anisotropic, soft
  | "porcelain" // smooth ceramic
  | "ceramic-tile" // slightly rougher ceramic
  | "glass-clear" // transparent, refractive
  | "paper" // matte, low-roughness
  | "rubber" // matte, slightly bouncy
  | "stone-marble" // polished stone
  | "stone-granite" // rougher stone
  | "paint-matte" // flat wall paint
  | "paint-satin" // eggshell wall paint
  | "carpet" // very rough fabric
  | "concrete"; // hard, rough, low-metal

/** Single texture descriptor (for the KTX2 delivery contract). */
export interface PBRTextureDescriptor {
  slot: PBRTextureSlot;
  /** Logical name; resolved at runtime to a /public/textures/<name>.ktx2 URL. */
  name: string;
  /** KTX2 supercompression (UASTC, ETC1S, or BC7). */
  compression: "UASTC" | "ETC1S" | "BC7";
  /** Color space; must match the slot. */
  colorSpace: ColorSpace;
  /** Texture dimensions (square, power of two preferred). */
  size: number;
  /** Mip levels (auto-generated from size). */
  mipLevels: number;
  /** Provenance (procedural seed, licensed asset, or "TBD"). */
  provenance: string;
}

/** Single PBR material slot declaration. */
export interface PBRMaterialSlot {
  class: PBRMaterialClass;
  /** Nominal base color in sRGB (will be decoded to linear at sample time). */
  baseColorSRGB: [number, number, number];
  /** Nominal metallic factor (0 = dielectric, 1 = metal). */
  metallic: number;
  /** Nominal roughness factor (0 = mirror, 1 = fully diffuse). */
  roughness: number;
  /** Optional sheen color (for fabric). */
  sheenColorSRGB?: [number, number, number];
  /** Optional sheen roughness (for fabric). */
  sheenRoughness?: number;
  /** IBL contribution: "strong" (metal / glass / wet) or "weak" (matte). */
  iblContribution: "strong" | "weak";
  /** Texture set: which texture slots this material fills. */
  textures: PBRTextureDescriptor[];
  /** Whether this material is transparent (alpha-blended, not alpha-tested). */
  transparent: boolean;
  /** Whether this material is double-sided. */
  doubleSided: boolean;
  /** Whether the material emits light. */
  emissive: boolean;
  /** Source-of-truth: catalog of materials, literal RGB values from material spec sheets. */
  provenance: string;
}

// ---------- Texture slot color-space assertions ----------
// These are glTF 2.0 spec requirements. The pipeline fails closed if violated.
const SLOT_COLOR_SPACE: Record<PBRTextureSlot, ColorSpace> = {
  baseColor: "srgb",
  normal: "linear",
  metallicRoughness: "linear",
  occlusion: "linear",
  emissive: "srgb",
  displacement: "linear",
  sheenColor: "srgb",
  sheenRoughness: "linear",
};

export function assertColorSpace(
  slot: PBRTextureSlot,
  declared: ColorSpace
): void {
  const required = SLOT_COLOR_SPACE[slot];
  if (required !== declared) {
    throw new Error(
      `PBR pipeline: texture slot '${slot}' requires color-space '${required}' ` +
        `but got '${declared}'. Per glTF 2.0 spec, color textures MUST be sRGB and ` +
        `data textures (normal, metallicRoughness, AO, displacement, sheenRoughness) ` +
        `MUST be linear. Fail-closed.`
    );
  }
}

// ---------- PBR material slot table ----------
// Source: Khronos PBR examples (https://www.khronos.org/gltf/pbr) + three.js PBR
// material defaults + the Apple RoomPlan 16-category taxonomy (for the
// per-furniture-kind mapping in `furnitureKindToPBRClass`).
//
// All baseColor values are sRGB 0-255 from material spec sheets; they are stored as
// 0-1 floats in this table. Roughness is in [0, 1]. Metallic is 0 (dielectric) or
// 1 (metal); for partial-metal (e.g., painted wood with brass handles) we use 0
// for the body and override per-piece.

export const PBR_MATERIAL_SLOTS: Record<PBRMaterialClass, PBRMaterialSlot> = {
  "oak-wood": {
    class: "oak-wood",
    baseColorSRGB: [0.545, 0.412, 0.078], // #8B6914 (Sears Modern Homes oak)
    metallic: 0.0,
    roughness: 0.5,
    iblContribution: "weak",
    textures: [
      {
        slot: "baseColor",
        name: "oak-wood-baseColor",
        compression: "UASTC",
        colorSpace: "srgb",
        size: 1024,
        mipLevels: 11,
        provenance: "procedural (per-cmaes-feat-pr2-proc-materials) seed oak-default",
      },
      {
        slot: "normal",
        name: "oak-wood-normal",
        compression: "UASTC",
        colorSpace: "linear",
        size: 1024,
        mipLevels: 11,
        provenance: "procedural ring-grain",
      },
      {
        slot: "metallicRoughness",
        name: "oak-wood-mr",
        compression: "UASTC",
        colorSpace: "linear",
        size: 512,
        mipLevels: 10,
        provenance: "procedural; metallic=0, roughness=0.5",
      },
      {
        slot: "occlusion",
        name: "oak-wood-ao",
        compression: "UASTC",
        colorSpace: "linear",
        size: 512,
        mipLevels: 10,
        provenance: "procedural",
      },
    ],
    transparent: false,
    doubleSided: false,
    emissive: false,
    provenance: "Sears Modern Homes catalog 1928 (oak)",
  },
  "walnut-wood": {
    class: "walnut-wood",
    baseColorSRGB: [0.36, 0.25, 0.2], // #5C4033
    metallic: 0.0,
    roughness: 0.45,
    iblContribution: "weak",
    textures: [
      {
        slot: "baseColor",
        name: "walnut-wood-baseColor",
        compression: "UASTC",
        colorSpace: "srgb",
        size: 1024,
        mipLevels: 11,
        provenance: "procedural (per-cmaes-feat-pr2-proc-materials) seed walnut-default",
      },
      {
        slot: "normal",
        name: "walnut-wood-normal",
        compression: "UASTC",
        colorSpace: "linear",
        size: 1024,
        mipLevels: 11,
        provenance: "procedural",
      },
      {
        slot: "metallicRoughness",
        name: "walnut-wood-mr",
        compression: "UASTC",
        colorSpace: "linear",
        size: 512,
        mipLevels: 10,
        provenance: "procedural; metallic=0, roughness=0.45",
      },
    ],
    transparent: false,
    doubleSided: false,
    emissive: false,
    provenance: "Sears Modern Homes catalog 1928 (walnut)",
  },
  brass: {
    class: "brass",
    baseColorSRGB: [0.722, 0.596, 0.353], // #B8985A
    metallic: 1.0,
    roughness: 0.25,
    iblContribution: "strong",
    textures: [
      {
        slot: "baseColor",
        name: "brass-baseColor",
        compression: "UASTC",
        colorSpace: "srgb",
        size: 512,
        mipLevels: 10,
        provenance: "procedural; warm metal",
      },
      {
        slot: "metallicRoughness",
        name: "brass-mr",
        compression: "UASTC",
        colorSpace: "linear",
        size: 512,
        mipLevels: 10,
        provenance: "procedural; metallic=1, roughness=0.25",
      },
    ],
    transparent: false,
    doubleSided: false,
    emissive: false,
    provenance: "Sears Modern Homes catalog 1928 (brass hardware)",
  },
  chrome: {
    class: "chrome",
    baseColorSRGB: [0.69, 0.72, 0.74], // #B0B8BC
    metallic: 1.0,
    roughness: 0.05,
    iblContribution: "strong",
    textures: [
      {
        slot: "baseColor",
        name: "chrome-baseColor",
        compression: "UASTC",
        colorSpace: "srgb",
        size: 512,
        mipLevels: 10,
        provenance: "procedural; cool polished metal",
      },
      {
        slot: "metallicRoughness",
        name: "chrome-mr",
        compression: "UASTC",
        colorSpace: "linear",
        size: 512,
        mipLevels: 10,
        provenance: "procedural; metallic=1, roughness=0.05",
      },
    ],
    transparent: false,
    doubleSided: false,
    emissive: false,
    provenance: "Modern consumer-grade (steel brushed)",
  },
  "cast-iron": {
    class: "cast-iron",
    baseColorSRGB: [0.165, 0.176, 0.196], // #2A2D32
    metallic: 1.0,
    roughness: 0.6,
    iblContribution: "strong",
    textures: [
      {
        slot: "baseColor",
        name: "cast-iron-baseColor",
        compression: "UASTC",
        colorSpace: "srgb",
        size: 512,
        mipLevels: 10,
        provenance: "procedural; rough dark metal",
      },
      {
        slot: "metallicRoughness",
        name: "cast-iron-mr",
        compression: "UASTC",
        colorSpace: "linear",
        size: 512,
        mipLevels: 10,
        provenance: "procedural; metallic=1, roughness=0.6",
      },
    ],
    transparent: false,
    doubleSided: false,
    emissive: false,
    provenance: "Modern consumer-grade (cast iron)",
  },
  "fabric-cotton": {
    class: "fabric-cotton",
    baseColorSRGB: [0.42, 0.482, 0.369], // #6B7B5E
    metallic: 0.0,
    roughness: 0.85,
    sheenColorSRGB: [0.42, 0.482, 0.369],
    sheenRoughness: 0.6,
    iblContribution: "weak",
    textures: [
      {
        slot: "baseColor",
        name: "fabric-cotton-baseColor",
        compression: "UASTC",
        colorSpace: "srgb",
        size: 512,
        mipLevels: 10,
        provenance: "procedural; plain weave",
      },
      {
        slot: "normal",
        name: "fabric-cotton-normal",
        compression: "UASTC",
        colorSpace: "linear",
        size: 512,
        mipLevels: 10,
        provenance: "procedural; weave bump",
      },
      {
        slot: "sheenColor",
        name: "fabric-cotton-sheenColor",
        compression: "UASTC",
        colorSpace: "srgb",
        size: 256,
        mipLevels: 9,
        provenance: "procedural; diffuse sheen",
      },
      {
        slot: "sheenRoughness",
        name: "fabric-cotton-sheenRoughness",
        compression: "UASTC",
        colorSpace: "linear",
        size: 256,
        mipLevels: 9,
        provenance: "procedural; sheen roughness 0.6",
      },
    ],
    transparent: false,
    doubleSided: false,
    emissive: false,
    provenance: "Sears Modern Homes catalog 1928 (upholstery)",
  },
  "fabric-velvet": {
    class: "fabric-velvet",
    baseColorSRGB: [0.4, 0.1, 0.3], // deep wine
    metallic: 0.0,
    roughness: 0.92,
    sheenColorSRGB: [0.7, 0.5, 0.6],
    sheenRoughness: 0.4,
    iblContribution: "weak",
    textures: [
      {
        slot: "baseColor",
        name: "fabric-velvet-baseColor",
        compression: "UASTC",
        colorSpace: "srgb",
        size: 512,
        mipLevels: 10,
        provenance: "procedural; velvet pile",
      },
      {
        slot: "sheenColor",
        name: "fabric-velvet-sheenColor",
        compression: "UASTC",
        colorSpace: "srgb",
        size: 256,
        mipLevels: 9,
        provenance: "procedural; iridescent sheen",
      },
    ],
    transparent: false,
    doubleSided: false,
    emissive: false,
    provenance: "20th century consumer-grade (velvet upholstery)",
  },
  "fabric-leather": {
    class: "fabric-leather",
    baseColorSRGB: [0.3, 0.2, 0.15], // dark brown
    metallic: 0.0,
    roughness: 0.55,
    iblContribution: "weak",
    textures: [
      {
        slot: "baseColor",
        name: "fabric-leather-baseColor",
        compression: "UASTC",
        colorSpace: "srgb",
        size: 512,
        mipLevels: 10,
        provenance: "procedural; grain pattern",
      },
      {
        slot: "normal",
        name: "fabric-leather-normal",
        compression: "UASTC",
        colorSpace: "linear",
        size: 512,
        mipLevels: 10,
        provenance: "procedural; grain bump",
      },
    ],
    transparent: false,
    doubleSided: false,
    emissive: false,
    provenance: "20th century consumer-grade (leather)",
  },
  porcelain: {
    class: "porcelain",
    baseColorSRGB: [0.94, 0.929, 0.902], // #F0EDE6
    metallic: 0.0,
    roughness: 0.15,
    iblContribution: "strong",
    textures: [
      {
        slot: "baseColor",
        name: "porcelain-baseColor",
        compression: "UASTC",
        colorSpace: "srgb",
        size: 512,
        mipLevels: 10,
        provenance: "procedural; smooth white",
      },
      {
        slot: "metallicRoughness",
        name: "porcelain-mr",
        compression: "UASTC",
        colorSpace: "linear",
        size: 512,
        mipLevels: 10,
        provenance: "procedural; metallic=0, roughness=0.15",
      },
    ],
    transparent: false,
    doubleSided: false,
    emissive: false,
    provenance: "Modern consumer-grade (porcelain)",
  },
  "ceramic-tile": {
    class: "ceramic-tile",
    baseColorSRGB: [0.784, 0.753, 0.69], // #C8C0B0
    metallic: 0.0,
    roughness: 0.35,
    iblContribution: "strong",
    textures: [
      {
        slot: "baseColor",
        name: "ceramic-tile-baseColor",
        compression: "UASTC",
        colorSpace: "srgb",
        size: 1024,
        mipLevels: 11,
        provenance: "procedural; tiled surface",
      },
      {
        slot: "normal",
        name: "ceramic-tile-normal",
        compression: "UASTC",
        colorSpace: "linear",
        size: 1024,
        mipLevels: 11,
        provenance: "procedural; grout lines",
      },
    ],
    transparent: false,
    doubleSided: false,
    emissive: false,
    provenance: "20th century consumer-grade (ceramic tile)",
  },
  "glass-clear": {
    class: "glass-clear",
    baseColorSRGB: [0.85, 0.9, 0.95], // clear glass
    metallic: 0.0,
    roughness: 0.02,
    iblContribution: "strong",
    textures: [],
    transparent: true,
    doubleSided: false,
    emissive: false,
    provenance: "Modern consumer-grade (clear glass)",
  },
  paper: {
    class: "paper",
    baseColorSRGB: [0.95, 0.93, 0.88], // off-white
    metallic: 0.0,
    roughness: 0.95,
    iblContribution: "weak",
    textures: [],
    transparent: false,
    doubleSided: true,
    emissive: false,
    provenance: "Generic paper / book / curtain material",
  },
  rubber: {
    class: "rubber",
    baseColorSRGB: [0.15, 0.15, 0.15], // black
    metallic: 0.0,
    roughness: 0.7,
    iblContribution: "weak",
    textures: [],
    transparent: false,
    doubleSided: false,
    emissive: false,
    provenance: "20th century consumer-grade (rubber)",
  },
  "stone-marble": {
    class: "stone-marble",
    baseColorSRGB: [0.92, 0.91, 0.89], // polished white
    metallic: 0.0,
    roughness: 0.15,
    iblContribution: "strong",
    textures: [
      {
        slot: "baseColor",
        name: "stone-marble-baseColor",
        compression: "UASTC",
        colorSpace: "srgb",
        size: 1024,
        mipLevels: 11,
        provenance: "procedural; veined marble",
      },
      {
        slot: "normal",
        name: "stone-marble-normal",
        compression: "UASTC",
        colorSpace: "linear",
        size: 1024,
        mipLevels: 11,
        provenance: "procedural",
      },
    ],
    transparent: false,
    doubleSided: false,
    emissive: false,
    provenance: "20th century consumer-grade (polished marble)",
  },
  "stone-granite": {
    class: "stone-granite",
    baseColorSRGB: [0.55, 0.55, 0.55], // grey speckled
    metallic: 0.0,
    roughness: 0.7,
    iblContribution: "weak",
    textures: [
      {
        slot: "baseColor",
        name: "stone-granite-baseColor",
        compression: "UASTC",
        colorSpace: "srgb",
        size: 1024,
        mipLevels: 11,
        provenance: "procedural; speckled granite",
      },
    ],
    transparent: false,
    doubleSided: false,
    emissive: false,
    provenance: "20th century consumer-grade (granite)",
  },
  "paint-matte": {
    class: "paint-matte",
    baseColorSRGB: [0.961, 0.941, 0.91], // #F5F0E8 (cream walls)
    metallic: 0.0,
    roughness: 0.92,
    iblContribution: "weak",
    textures: [
      {
        slot: "baseColor",
        name: "paint-matte-baseColor",
        compression: "UASTC",
        colorSpace: "srgb",
        size: 1024,
        mipLevels: 11,
        provenance: "procedural; matte wall paint",
      },
    ],
    transparent: false,
    doubleSided: false,
    emissive: false,
    provenance: "Sears Modern Homes catalog 1928 (cream wall paint)",
  },
  "paint-satin": {
    class: "paint-satin",
    baseColorSRGB: [0.94, 0.92, 0.88],
    metallic: 0.0,
    roughness: 0.55,
    iblContribution: "weak",
    textures: [],
    transparent: false,
    doubleSided: false,
    emissive: false,
    provenance: "20th century consumer-grade (eggshell paint)",
  },
  carpet: {
    class: "carpet",
    baseColorSRGB: [0.545, 0.49, 0.42], // #8B7D6B
    metallic: 0.0,
    roughness: 0.95,
    iblContribution: "weak",
    textures: [
      {
        slot: "baseColor",
        name: "carpet-baseColor",
        compression: "UASTC",
        colorSpace: "srgb",
        size: 1024,
        mipLevels: 11,
        provenance: "procedural; carpet pile",
      },
    ],
    transparent: false,
    doubleSided: true,
    emissive: false,
    provenance: "20th century consumer-grade (carpet)",
  },
  concrete: {
    class: "concrete",
    baseColorSRGB: [0.75, 0.74, 0.72],
    metallic: 0.0,
    roughness: 0.85,
    iblContribution: "weak",
    textures: [
      {
        slot: "baseColor",
        name: "concrete-baseColor",
        compression: "UASTC",
        colorSpace: "srgb",
        size: 1024,
        mipLevels: 11,
        provenance: "procedural",
      },
    ],
    transparent: false,
    doubleSided: false,
    emissive: false,
    provenance: "20th century consumer-grade (concrete floor)",
  },
};

/** Default FurnitureKind -> PBRMaterialClass mapping.
 *  One or two classes per kind; consumers pick the right one (e.g., a chair's
 *  frame is wood but its cushion is fabric). */
export const FURNITURE_KIND_TO_PBR_CLASSES: Record<FurnitureKind, PBRMaterialClass[]> = {
  sofa: ["fabric-cotton", "oak-wood"],
  armchair: ["fabric-cotton", "fabric-leather", "oak-wood"],
  "dining-chair": ["oak-wood"],
  "bar-stool": ["chrome", "oak-wood"],
  "rocking-chair": ["oak-wood"],
  "dining-table": ["oak-wood"],
  "coffee-table": ["oak-wood", "brass"],
  "side-table": ["oak-wood", "brass"],
  desk: ["oak-wood", "brass"],
  "console-table": ["oak-wood"],
  dresser: ["oak-wood", "brass"],
  bookshelf: ["oak-wood"],
  cabinet: ["oak-wood", "brass"],
  wardrobe: ["walnut-wood", "brass"],
  pantry: ["oak-wood", "brass"],
  "twin-bed": ["fabric-cotton", "oak-wood"],
  "queen-bed": ["fabric-cotton", "oak-wood"],
  "bunk-bed": ["oak-wood"],
  crib: ["oak-wood"],
  fridge: ["chrome", "glass-clear"],
  oven: ["cast-iron", "chrome"],
  "range-hood": ["chrome"],
  dishwasher: ["chrome"],
  microwave: ["chrome", "glass-clear"],
  washer: ["chrome", "glass-clear"],
  dryer: ["chrome"],
  sink: ["porcelain", "chrome"],
  toilet: ["porcelain"],
  bathtub: ["porcelain"],
  shower: ["ceramic-tile", "glass-clear"],
  vanity: ["oak-wood", "porcelain", "brass", "stone-marble"],
  lamp: ["brass", "fabric-cotton"],
  rug: ["fabric-velvet", "carpet"],
  curtain: ["fabric-cotton"],
  "picture-frame": ["oak-wood", "glass-clear", "paint-matte"],
  plant: ["concrete", "fabric-cotton", "paint-satin"],
  plate: ["porcelain"],
  glass: ["glass-clear"],
  mug: ["porcelain"],
  bottle: ["glass-clear"],
  pan: ["cast-iron"],
  book: ["paper"],
  grill: ["cast-iron", "chrome"],
  "patio-chair": ["oak-wood"],
  planter: ["concrete"],
  "hose-reel": ["chrome"],
  "pet-cat": ["fabric-cotton"],
  "person-silhouette": ["fabric-cotton"],
};

/** Resolve the PBR material slot list for a given furniture kind. */
export function materialSlotsForKind(kind: FurnitureKind): PBRMaterialSlot[] {
  const classes = FURNITURE_KIND_TO_PBR_CLASSES[kind];
  return classes.map((c) => PBR_MATERIAL_SLOTS[c]);
}

/** Total texture-set budget across the PBR material table (sum of all texture
 *  descriptors, in MB assuming UASTC @ 8 bpp). Used by the Vercel bundle check. */
export function totalTextureBudgetMB(): number {
  let total = 0;
  for (const slot of Object.values(PBR_MATERIAL_SLOTS)) {
    for (const tex of slot.textures) {
      // UASTC: 8 bpp; ETC1S: 4 bpp; BC7: 8 bpp
      const bpp = tex.compression === "ETC1S" ? 4 : 8;
      // Mip-map chain: factor = 4/3 of base
      const basePixels = tex.size * tex.size;
      const totalPixels = basePixels * (4 / 3);
      total += (totalPixels * bpp) / 8 / 1024 / 1024; // bytes -> MB
    }
  }
  return total;
}

/** All PBR material classes. */
export const ALL_PBR_MATERIAL_CLASSES: PBRMaterialClass[] = Object.keys(
  PBR_MATERIAL_SLOTS
) as PBRMaterialClass[];
